#!/usr/bin/env bash

link=${BASH_SOURCE[0]}
this=${BASH_SOURCE[0]}

while [ -L $this ]; do 
    this=$(readlink $this)
done

source $(dirname $(dirname $this))/init/init.sh

this-main "$@"

$this_fin $this_err
